<table id="Tabelle_01" width="800" border="0" cellpadding="0"
	cellspacing="0">
	<tr>
		<td><img id="Unbenannt_1_01" src="/media/game/worldmap/Unbenannt-1_01.png"
			width="201" height="201" alt="" />
		</td>
		<td><img id="Unbenannt_1_02" src="/media/game/worldmap/Unbenannt-1_02.png"
			width="199" height="201" alt="" />
		</td>
		<td><img id="Unbenannt_1_03" src="/media/game/worldmap/Unbenannt-1_03.png"
			width="201" height="201" alt="" />
		</td>
		<td><img id="Unbenannt_1_04" src="/media/game/worldmap/Unbenannt-1_04.png"
			width="199" height="201" alt="" />
		</td>
	</tr>
	<tr>
		<td><img id="Unbenannt_1_05" src="/media/game/worldmap/Unbenannt-1_05.png"
			width="201" height="199" alt="" />
		</td>
		<td><img id="Unbenannt_1_06" src="/media/game/worldmap/Unbenannt-1_06.png"
			width="199" height="199" alt="" />
		</td>
		<td><img id="Unbenannt_1_07" src="/media/game/worldmap/Unbenannt-1_07.png"
			width="201" height="199" alt="" />
		</td>
		<td><img id="Unbenannt_1_08" src="/media/game/worldmap/Unbenannt-1_08.png"
			width="199" height="199" alt="" />
		</td>
	</tr>
	<tr>
		<td><img id="Unbenannt_1_09" src="/media/game/worldmap/Unbenannt-1_09.png"
			width="201" height="202" alt="" />
		</td>
		<td><img id="Unbenannt_1_10" src="/media/game/worldmap/Unbenannt-1_10.png"
			width="199" height="202" alt="" />
		</td>
		<td><img id="Unbenannt_1_11" src="/media/game/worldmap/Unbenannt-1_11.png"
			width="201" height="202" alt="" />
		</td>
		<td><img id="Unbenannt_1_12" src="/media/game/worldmap/Unbenannt-1_12.png"
			width="199" height="202" alt="" />
		</td>
	</tr>
	<tr>
		<td><img id="Unbenannt_1_13" src="/media/game/worldmap/Unbenannt-1_13.png"
			width="201" height="198" alt="" />
		</td>
		<td><img id="Unbenannt_1_14" src="/media/game/worldmap/Unbenannt-1_14.png"
			width="199" height="198" alt="" />
		</td>
		<td><img id="Unbenannt_1_15" src="/media/game/worldmap/Unbenannt-1_15.png"
			width="201" height="198" alt="" />
		</td>
		<td><img id="Unbenannt_1_16" src="/media/game/worldmap/Unbenannt-1_16.png"
			width="199" height="198" alt="" />
		</td>
	</tr>
</table>
