<div class="simpleList" style="float:left;">
	<p class="listHeading">List of all Players</p>
	<?php foreach ($this->players as $entry): ?>
	<?php $this->placeholder('userName')->set($entry->name); ?>
	<?php $this->placeholder('playerLocation')->set($entry->getLocation().'('.$entry->areaId.')'); ?>
	<div class="player">
		<?php echo '<span class="playerName" title="'.$entry->id.'">Name '.$entry->name.'</span>&nbsp;&nbsp;'; ?>
		<span class="playerHealth" ><?php echo "Health ".$entry->health."&nbsp;&nbsp;"; ?></span>
		<span class="playerAttackDamage" ><?php echo "AD ".$entry->attackDamage."&nbsp;&nbsp;"; ?></span>
		<span class="playerExperience" ><?php echo "XP ".$entry->experience."&nbsp;&nbsp;"; ?></span>
	</div>
	<?php endforeach; ?>
</div>
<div class="simpleList" style="float:right;">
	<p class="listHeading">List of all Monsters</p>
	<?php foreach ($this->entries as $entry): ?>
	<div class="monster">
		<span class="monsterName" ><?php echo $entry->name; ?></span>
		<span class="monsterHealth" ><?php echo "&nbsp;&nbsp;&nbsp;".$entry->health."&nbsp;&nbsp;"; ?></span>
		<span class="monsterAttackDamage" ><?php echo $entry->attackDamage."&nbsp;&nbsp;"; ?></span>
		<span><?php echo $entry->id; ?></span>
		<button class='attack-button' id="<?php echo $entry->id; ?>">Attack</button>
	</div>
	<?php endforeach; ?>
</div>
<div id="content" style="clear:both;visibility:hidden;"></div>
