<style>
    a:link,
    a:visited
    {
        color: #0398CA;
    }

    span#zf-name
    {
        color: #91BE3F;
    }

    div#welcome
    {
        color: #FFFFFF;
        background-image: url(http://framework.zend.com/images/bkg_header.jpg);
        width:  600px;
        height: 400px;
        border: 2px solid #444444;
        overflow: hidden;
        text-align: center;
    }

    div#more-information
    {
        background-image: url(http://framework.zend.com/images/bkg_body-bottom.gif);
        height: 100%;
    }
    
    p.listHeading
    {
    	background-color:lightgrey;
    }
    
    span.headBarText
    {
    	color:white;
    	font-family: Verdana;
    }
    
    div.simpleList
    {
    	max-width:450px;
    }
    
    div.headBar
    {
    	background-color:black;
    	height:60px;
    	padding-top:10px;
    	padding-left:70px;
    }
    
</style>
<div class="headBar" >
	<span class="headBarText" >Main - Profile - Battle - Quest</span>
</div>
<div class="simpleList" style="float:left;">
	<p class="listHeading">List of all Players</p>
	<?php foreach ($this->players as $entry): ?>
	<br />
	<?php 
		echo '<span title="'.$entry->id.'">Name '.$entry->name.'</span>&nbsp;&nbsp;';
		echo "Health ".$entry->health."&nbsp;&nbsp;";
		echo "AD ".$entry->attackDamage."&nbsp;&nbsp;";
		echo "XP ".$entry->experience."&nbsp;&nbsp;";
	?>
	<br />
	<?php endforeach; ?>
</div>
<div class="simpleList" style="margin-left:290px;padding-left:90px;">
	<p class="listHeading">List of all Monsters</p>
	<?php foreach ($this->entries as $entry): ?>
	<br />
	<?php 
		echo $this->ajaxLink("Attack ".$entry->name,
							'/monster/attack/id/'.$entry->id,
							array('update' => '#content', 'noscript' => false, 'dataType' => 'Html',
							 'beforeSend' => 'loadingBattle();', 'complete' => 'loadingBattleFinished();')
								);
		echo "&nbsp;&nbsp;&nbsp;".$entry->health."&nbsp;&nbsp;";
		echo $entry->attackDamage."&nbsp;&nbsp;";
	?>
	<br />
	<?php endforeach; ?>
</div>
<div id="content" style="clear:both">
</div>
