
<div class="simpleList" style="float:left;">
	<p class="listHeading">List of all Players</p>
	<?php foreach ($this->players as $entry): ?>
	<br />
	<?php 
		echo '<span title="'.$entry->id.'">Name '.$entry->name.'</span>&nbsp;&nbsp;';
		echo "Health ".$entry->health."&nbsp;&nbsp;";
		echo "AD ".$entry->attackDamage."&nbsp;&nbsp;";
		echo "XP ".$entry->experience."&nbsp;&nbsp;";
	?>
	<br />
	<?php endforeach; ?>
</div>
<div class="simpleList" style="margin-left:290px;padding-left:90px;">
	<p class="listHeading">List of all Monsters</p>
	<?php foreach ($this->entries as $entry): ?>
	<br />
	<?php 
		echo $this->ajaxLink("Attack ".$entry->name,
							'/monster/attack/id/'.$entry->id,
							array('update' => '#content', 'noscript' => false, 'dataType' => 'Html',
							 'beforeSend' => 'loadingBattle();', 'complete' => 'loadingBattleFinished();')
								);
		echo "&nbsp;&nbsp;&nbsp;".$entry->health."&nbsp;&nbsp;";
		echo $entry->attackDamage."&nbsp;&nbsp;";
	?>
	<br />
	<?php endforeach; ?>
</div>
<div id="content" style="clear:both">
</div>
