<div id="battleFrame">
	<div id="monster" >
		<img src="" alt="monster picture" />
	</div>
	<div id="battleLog" style="background-color:black; padding:2px 2px 2px 2px;max-height:104px;height:104px;min-height:104px;">
		<div style="background-color:white; padding:2px 2px 2px 2px;max-height:100px;height:100px;min-height:100px;overflow-x:hidden;overflow-y:scroll;">
			<div><span>11:11:19: You hit the Groll for <span style="color:red;" >10 Magic(Fire) damage</span>!</span></div>
			<div><span>11:12:39: You used <span style="color:green;" >Heal(Spell)</span> to restore <span style="color:red;" >10 LP(Life Points)!</span></span></div>
			<div><span>11:11:19: You hit the Groll for <span style="color:red;" >10 Magic(Fire) damage</span>!</span></div>
			<div><span>11:12:39: You used <span style="color:green;" >Heal(Spell)</span> to restore <span style="color:red;" >10 LP(Life Points)!</span></span></div>
			<div><span>11:11:19: You hit the Groll for <span style="color:red;" >10 Magic(Fire) damage</span>!</span></div>
			<div><span>11:12:39: You used <span style="color:green;" >Heal(Spell)</span> to restore <span style="color:red;" >10 LP(Life Points)!</span></span></div>
			<div><span>11:11:19: You hit the Groll for <span style="color:red;" >10 Magic(Fire) damage</span>!</span></div>
			<div><span>11:12:39: You used <span style="color:green;" >Heal(Spell)</span> to restore <span style="color:red;" >10 LP(Life Points)!</span></span></div>
			<div><span>11:11:19: You hit the Groll for <span style="color:red;" >10 Magic(Fire) damage</span>!</span></div>
			<div><span>11:12:39: You used <span style="color:green;" >Heal(Spell)</span> to restore <span style="color:red;" >10 LP(Life Points)!</span></span></div>
		</div>
	</div>
	<div id="player" >
		<img src="" alt="player picture" />
		<div id="playerSpellbar">
			<div id="playerSpells">
				<div class="spell"><button>Heal</button></div>
				<div class="spell"><button>Melee Attack</button></div>
				<div class="spell"><button>Ranged Attack</button></div>
				<div class="spell"><button>Shield</button></div>
				<br />
			</div>
		</div>
	</div>
</div>