<div id="home">
	<div class="playerStats" >
			<div class="playerStatRow"><div class="container"><span class="playerStatName" >Hero</span><span class="playerStat" id="playerHero" ><?php echo $this->player->hero; ?></span></div><br /></div>
			<div class="playerStatRow"><div class="container"><span class="playerStatName" >Health</span><span class="playerStat" id="playerHealth" ><?php echo $this->player->health; ?></span></div><br /></div>
			<div class="playerStatRow"><div class="container"><span class="playerStatName" >Mana</span><span class="playerStat" id="playerMana" ><?php echo $this->player->mana; ?></span></div><br /></div>
			<div class="playerStatRow"><div class="container"><span class="playerStatName" >Attack Damage</span><span class="playerStat" id="playerAttackDamage" ><?php echo $this->player->attackDamage; ?></span></div><br /></div>
			<div class="playerStatRow"><div class="container"><span class="playerStatName" >Defense</span><span class="playerStat" id="playerDefense" ><?php echo $this->player->defense; ?></span></div><br /></div>
			<div class="playerStatRow"><div class="container"><span class="playerStatName" >Experience</span><span class="playerStat" id="playerExperience" ><?php echo $this->player->experience; ?></span></div><br /></div>
			<div class="playerStatRow"><div class="container"><span class="playerStatName" >Location</span><span class="playerStat" id="playerLocation" ><?php echo $this->player->location; ?></span></div><br /></div>
	</div>
</div>