<div>
	<span><?php echo $this->player->name; ?></span><br />
	<span><?php echo $this->player->health; ?></span><br />
	<span><?php echo $this->player->hero; ?></span><br />
	<span><?php echo $this->player->mana; ?></span><br />
	<span><?php echo $this->player->attackDamage; ?></span><br />
	<span><?php echo $this->player->defense; ?></span><br />
	<span><?php echo $this->player->experience; ?></span><br />
</div>

<br /><br /><center>View script for controller <b>player</b> and script/action name <b>profile</b></center>
