<?php echo $this->doctype()."\n"; ?>
<html>
<head>
<?php 
	echo $this->jQuery()
	->enable()->uiEnable()
	->addJavascriptFile('/webscripts/getscript/script/battle.js')
	->addJavascriptFile('/webscripts/getscript/script/main.js')
	->addOnLoad('IrontouchGameSetup();');
?>

<style>
    a:link,
    a:visited
    {
        color: #0398CA;
    }

    span#zf-name
    {
        color: #91BE3F;
    }

    div#welcome
    {
        color: #FFFFFF;
        background-image: url(http://framework.zend.com/images/bkg_header.jpg);
        width:  600px;
        height: 400px;
        border: 2px solid #444444;
        overflow: hidden;
        text-align: center;
    }

    div#more-information
    {
        background-image: url(http://framework.zend.com/images/bkg_body-bottom.gif);
        height: 100%;
    }
    
    p.listHeading
    {
    	background-color:lightgrey;
    }
    
    a.headBarLink
    {
    	font-family: Verdana;
    }
    
    span.headBarUserText
    {
    	font-family: Verdana;
    }
    
    span.headBarTitle
    {
    	font-family: Calibri;
    	font-size:36px;
    	text-shadow: 1px 1px 1px #999999, 5px 3px 2px #CCCCCC;
    	float:left;
    	margin-bottom:10px;
    }
  
    div.simpleList
    {
    	max-width:450px;
    }
    
    div.headBar
    {
    	padding-top:10px;
    	padding-left:70px;
    }
    
    div.innerHeadBar
    {
    	background-color:black;
    	width:auto;
    	height:auto;
    }
    
    div.contentBox
    {
    	padding-top:50px;
    	padding-left:80px;
    }
    
    div.headBarUser
    {
    	padding: 7px 7px 7px 7px;
    	float:right;
    	background-color:lightgrey;
    }
    div.headBarText
    {
    	padding: 5px 5px 5px 5px;
    }
    
    .shadow 
    {
	  text-shadow: 1px 1px 1px #BBFFFF;
	}
	
	#loadingBattle
	{
		background-color:lightgrey;
		border-width:10px;
		border-color:lightgrey;
		margin-left:40%;
		float:left;
	}
    .html5logo
    {
    	float:right;
    }
    .clear
    {
    	clear:both;
    }
</style>
</head>
<body>
<div class="headBar" >
	<span class="headBarTitle">SimpleRPG</span>
	<div id="loadingBattle" style="text-align:center;"><img alt="loading.png" src="/media/1306503198_process.png"><span style="font-weight:bold;color:white;" >battling monster...</span></div>
	<div class="html5logo"><img alt="HTML5logowhite" src="http://www.w3.org/html/logo/downloads/HTML5_Logo_32.png"></div>
	<dir class="clear"></dir>
		<div class="innerHeadBar">
			<div class="headBarText" >
				<a class="headBarLink" href="<?php echo $this->url(array('action' => '', 'controller' => 'index')); ?>" >Home</a>
				<a class="headBarLink" href="<?php echo $this->url(array('action' => 'profile', 'controller' => 'player')); ?>" >Profile</a>
			</div>
		</div>
		<div class="headBarUser" >
				<?php echo $this->gravatar("info@accountr.eu"); ?><br />
				<span class="headBarUserText">Your are: <?php echo $this->placeholder('userName'); ?></span>
		</div>
		<div class="clear"></div>
</div>
<div class="clear"></div>
<div class="contentBox">
	<?php echo $this->layout()->content; ?>
</div>
</body>
</html>