<?php if($this->alreadyAccepted): ?>
<div>
	<span>You've already accepted this quest!</span>
</div>
<?php endif; ?>
<?php if(!$this->alreadyAccepted): ?>
<div id="quest" >
	<div class="questTitle" >
		<div class="questHeadBar" ></div>
		<div style="float:left;background-image: url('/media/game/tavern-sign-small.png');background-repeat:no-repeat;background-position:center; 
				width:170px;height:80px;max-height:80px;margin-top:-20px;">
			<div class="innerQuestTitle"><span class="questTitle" >"<u><?php echo $this->quest->title; ?></u>"</span></div>
		</div>
		<div style="float:right;margin-right:20px;margin-top:10px;" ><img class="questSign" src="/media/game/quest-sign-small.png" alt="questsign" ></div>
		<div class="clear"></div>
	</div>
	<div class="clear"></div>
	<div class="questContent" ><?php echo $this->quest->content; ?></div>
	<div class="questObjective" style="padding:15px 15px 15px 15px" >
		<div style="float:right;">
			<span>Slay:</span>
			<div class="questObjectiveMonster" style="border-style:solid;border-width:5px;height:80px;width:160px;border-color:lightgreen;" ><?php echo $this->quest->monsterList[0]; ?></div>
		</div>
		<br />
	</div>
	<div class="questRewards" ><span>Experience: <?php echo $this->quest->experience;?> Gold: <?php echo $this->quest->gold; ?></span></div>
	<div class="questControls" >
		<form method="POST" action="<?php echo $this->url(array('action' => 'accept', 'controller' => 'quest', 'id' => $this->quest->id, 'playerId' => 1)); ?>" >
			<button type="submit" >Accept this great offer!</button>
		</form>
	</div>
</div>
<?php endif; ?>